
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Fixed chatPanel;
	private global::Gtk.ScrolledWindow messagesPanel;
	private global::Gtk.ScrolledWindow sendPanel;
	private global::Gtk.TextView sendText;
	private global::Gtk.Button sendButton;
	private global::Gtk.Label sendLabel;
	private global::Gtk.Label usernameLabel;
	private global::Gtk.Button connectButton;
	private global::Gtk.Entry usernameBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 800;
		this.HeightRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.chatPanel = new global::Gtk.Fixed ();
		this.chatPanel.Name = "chatPanel";
		this.chatPanel.HasWindow = false;
		// Container child chatPanel.Gtk.Fixed+FixedChild
		this.messagesPanel = new global::Gtk.ScrolledWindow ();
		this.messagesPanel.WidthRequest = 830;
		this.messagesPanel.HeightRequest = 450;
		this.messagesPanel.Sensitive = false;
		this.messagesPanel.Name = "messagesPanel";
		this.messagesPanel.ShadowType = ((global::Gtk.ShadowType)(1));
		this.chatPanel.Add (this.messagesPanel);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.chatPanel [this.messagesPanel]));
		w1.X = 20;
		w1.Y = 50;
		// Container child chatPanel.Gtk.Fixed+FixedChild
		this.sendPanel = new global::Gtk.ScrolledWindow ();
		this.sendPanel.WidthRequest = 730;
		this.sendPanel.Name = "sendPanel";
		this.sendPanel.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child sendPanel.Gtk.Container+ContainerChild
		this.sendText = new global::Gtk.TextView ();
		this.sendText.Sensitive = false;
		this.sendText.CanFocus = true;
		this.sendText.Name = "sendText";
		this.sendPanel.Add (this.sendText);
		this.chatPanel.Add (this.sendPanel);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.chatPanel [this.sendPanel]));
		w3.X = 20;
		w3.Y = 530;
		// Container child chatPanel.Gtk.Fixed+FixedChild
		this.sendButton = new global::Gtk.Button ();
		this.sendButton.WidthRequest = 80;
		this.sendButton.Sensitive = false;
		this.sendButton.CanFocus = true;
		this.sendButton.Events = ((global::Gdk.EventMask)(512));
		this.sendButton.Name = "sendButton";
		this.sendButton.UseUnderline = true;
		this.sendButton.Label = global::Mono.Unix.Catalog.GetString ("Send");
		this.chatPanel.Add (this.sendButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.chatPanel [this.sendButton]));
		w4.X = 770;
		w4.Y = 530;
		// Container child chatPanel.Gtk.Fixed+FixedChild
		this.sendLabel = new global::Gtk.Label ();
		this.sendLabel.Name = "sendLabel";
		this.sendLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Message:");
		this.chatPanel.Add (this.sendLabel);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.chatPanel [this.sendLabel]));
		w5.X = 20;
		w5.Y = 508;
		// Container child chatPanel.Gtk.Fixed+FixedChild
		this.usernameLabel = new global::Gtk.Label ();
		this.usernameLabel.Name = "usernameLabel";
		this.usernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
		this.chatPanel.Add (this.usernameLabel);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.chatPanel [this.usernameLabel]));
		w6.X = 20;
		w6.Y = 10;
		// Container child chatPanel.Gtk.Fixed+FixedChild
		this.connectButton = new global::Gtk.Button ();
		this.connectButton.CanFocus = true;
		this.connectButton.Name = "connectButton";
		this.connectButton.UseUnderline = true;
		this.connectButton.Label = global::Mono.Unix.Catalog.GetString ("Connect");
		this.chatPanel.Add (this.connectButton);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.chatPanel [this.connectButton]));
		w7.X = 275;
		w7.Y = 5;
		// Container child chatPanel.Gtk.Fixed+FixedChild
		this.usernameBox = new global::Gtk.Entry ();
		this.usernameBox.CanFocus = true;
		this.usernameBox.Name = "usernameBox";
		this.usernameBox.IsEditable = true;
		this.usernameBox.InvisibleChar = '●';
		this.chatPanel.Add (this.usernameBox);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.chatPanel [this.usernameBox]));
		w8.X = 100;
		w8.Y = 5;
		this.Add (this.chatPanel);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 867;
		this.DefaultHeight = 600;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
